// <auto-generated/>
namespace Application;

using System.Diagnostics.Metrics;

public static partial class Metrics
{
	public struct WarehouseConveyorProcessedTags
	{
		
		[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse_conveyor_error")]
		public string WarehouseConveyorError { get; set; }
		
		[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse_conveyor_id")]
		public required string WarehouseConveyorId { get; set; }
		
		[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse_item_type")]
		public required WarehouseItemType WarehouseItemType { get; set; }
		
		[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse_conveyor_operator_id")]
		public string WarehouseConveyorOperatorId { get; set; }
	}


	[global::Microsoft.Extensions.Diagnostics.Metrics.Counter<double>(typeof(WarehouseConveyorProcessedTags), Name = "warehouse_conveyor_processed_total")]
	public static partial WarehouseConveyorProcessedMetric CreateWarehouseConveyorProcessed(Meter meter);


}