// <auto-generated/>
namespace Application;

// Required namespace reference
using global::System.Diagnostics.Metrics;

public static partial class Metrics
{
    public struct WarehouseConveyorProcessedTags
    {
    	[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse.conveyor.error")]
    	public string WarehouseConveyorError { get; set; }
    	[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse.conveyor.id")]
    	public required string WarehouseConveyorId { get; set; }
    	[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse.item.type")]
    	public required WarehouseItemType WarehouseItemType { get; set; }
    	[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse.conveyor.operator_id")]
    	public string WarehouseConveyorOperatorId { get; set; }
    }
    
    [global::Microsoft.Extensions.Diagnostics.Metrics.Counter<double>(typeof(WarehouseConveyorProcessedTags), Name = "warehouse.conveyor.processed.total")]
    public static partial WarehouseConveyorProcessedMetric CreateWarehouseConveyorProcessed(Meter meter);

    public struct WarehouseConveyorActiveTags
    {
    	[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse.conveyor.id")]
    	public string WarehouseConveyorId { get; set; }
    	[global::Microsoft.Extensions.Diagnostics.Metrics.TagName("warehouse.conveyor.operator_id")]
    	public string WarehouseConveyorOperatorId { get; set; }
    }
    
    [global::Microsoft.Extensions.Diagnostics.Metrics.Gauge<double>(typeof(WarehouseConveyorActiveTags), Name = "warehouse.conveyor.active")]
    public static partial WarehouseConveyorActiveMetric CreateWarehouseConveyorActive(Meter meter);

}